//Not logged in
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_MESSAGE_BY_ID = 'GET_MESSAGE_BY_ID';
export const FILTER_MESSAGES_BY_CONTENT = 'GET_MESSAGE_BY_CONTENT';
export const GET_MESSAGE_BY_CONTENT_AND_CATEGORIE = 'GET_MESSAGE_BY_CONTENT_AND_CATEGORIE';

//Logged in
export const UPVOTE_BY_MESSAGE_ID = 'UPVOTE_BY_MESSAGE_ID';
export const DOWNVOTE_BY_MESSAGE_ID = 'DOWNVOTE_BY_MESSAGE_ID';

//API Calls
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_COMMENTS_BY_ID = 'FETCH_COMMENTS_BY_ID';
export const POST_COMMENT_BY_MESSAGE_ID = 'POST_COMMENT_BY_MESSAGE_ID';
export const UPVOTE_MESSAGE = 'UPVOTE_MESSAGE';
export const DOWNVOTE_MESSAGE = 'DOWNVOTE_MESSAGE_';
export const FETCH_MESSAGE_BY_ID = 'FETCH_MESSAGE_BY_ID';
export const FETCH_MESSAGES_BY_CONTENT = 'FETCH_MESSAGES_BY_CONTENT';
export const FETCH_MESSAGES_BY_CONTENT_AND_CATEGORY = 'FETCH_MESSAGES_BY_CONTENT_AND_CATEGORY';


export const SELECT_CATEGORY = 'SELECT_CATEGORY';

//Login
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';